<?php

namespace App\Http\Repositories;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class UserRepositories extends BaseRepository
{

	protected Model $model;

	public function __construct(User $model)
	{
		parent::__construct($model);

		$this->model = $model;
	}

	public function create(array $payload): ?Model
	{
		return parent::create($payload); // TODO: Change the autogenerated stub
	}

}
